twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        static_url: '%env(STATIC_URL)%'
        menu: '%menu%'
    exception_controller: App\Controller\ExceptionController:showAction
