check:
    stage: check
    image: rogerclotet/php7-symfony
    cache:
        paths:
            - vendor/
            - .php_cs.cache
    script:
        - composer install
        - bin/console doctrine:schema:update --env=test --force
        - make check-ci

assets:
    stage: build
    image: kkarczmarczyk/node-yarn
    script:
        - yarn install
        - yarn encore production
    artifacts:
        paths:
            - public/build
    only:
        - master
        - tags

staging:
    stage: deploy
    image: ruby:2.4
    dependencies:
        - assets
    script:
        - gem install dpl
        - dpl --provider=heroku --skip_cleanup --app=jaarribaremclub-staging --api-key=$HEROKU_API_KEY
    only:
        - master

#production:
#    stage: deploy
#    image: ruby:2.4
#    dependencies:
#        - assets
#    script:
#        - gem install dpl
#        - dpl --provider=heroku --skip_cleanup --app=jaarribaremclub --api-key=$HEROKU_API_KEY
#    only:
#        - tags

stages:
    - check
    - build
    - deploy
