version: '2'

services:
  php:
    image: rogerclotet/php7-symfony
    volumes:
      - ./:/code:cached
      - ./var/log/symfony:/var/www/symfony/var/logs:cached
    working_dir: /code

  nginx:
    build: docker/nginx
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./var/log/nginx/:/var/log/nginx:cached
