doctrine:
    dbal:
        driver: pdo_sqlite
        charset: UTF8
        path: "%kernel.root_dir%/../var/data.sqlite"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
